version: "3"
services:
  server:
    image: jetbrains/teamcity-server:2020.2.2
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
      - /var/run/docker.sock:/var/run/docker.sock
  teamcity-agent:
    image: jetbrains/teamcity-agent:2019.2.4
    user: root
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=regular_agent
      - DOCKER_IN_DOCKER=start
    volumes:
      - ./teamcity_agent_conf:/data/teamcity_agent/conf