apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: asphelloworld
  namespace: monitoring
  labels:
    app: asphelloworld
    release: prometheus
spec:
  selector:
    matchLabels:
      app: asphelloworld
  jobLabel: app
  endpoints:
    - port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - default