apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: aspnethelloworld-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: asphelloworld-service
              servicePort: 80
            path: /something(/|$)(.*)