apiVersion: apps/v1
kind: Deployment
metadata:
  name: asphelloworld-deployment
  labels:
    app: asphelloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asphelloworld
  template:
    metadata:
      labels:
        app: asphelloworld
    spec:
      containers:
        - name: asphelloworld
          image: $HELLO_WORLD_IMAGE
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: asphelloworld-service
  labels:
    app: asphelloworld
spec:
  selector:
    app: asphelloworld
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80